name: deploy-chabokan
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: "22"
      - name: update-chabokan
        env:
          CHABOKAN_TOKEN: ${{ secrets.CHABOKAN_TOKEN }}
        run: |
          npm install -g @chabokan.net/cli
          chabok login -t $CHABOKAN_TOKEN
          npm i
          npm run build
          cd dist/
          chabok deploy -s torbatti-ir